name: student_exam_predictor
description: A Flutter app that predicts student exam scores using an API.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  google_fonts: 4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1



flutter:
  uses-material-design: true
